# Matemática para Ciencia de los Datos
# Trabajo Práctico 4

Profesor: Juan Luis Crespo Mariño (basado en trabajo previo del Prof. Dr. Luis Alexánder Calvo Valverde)

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 5 de Noviembre del 2024, a más tardar a las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. Jonathan Chavarria Miranda
1. Felipe Quesada Miranda



---

## Parte 1

Dada la siguiente matriz:

\begin{equation}
A= \begin{bmatrix}
   1.,2. \\
   3.,4.
\end{bmatrix}
\end{equation}




**Ejercicio 1.1 (25 puntos)**

En una celda de texto, calcule los auto-valores y deje planteada la ecuación para el cálculo de los los auto-vectores como los ejemplos vistos en clase. Debe mostrar todo el procedimiento.

Para una matriz cuadrada A, los autovalores $\lambda$ son las soluciones de la ecuación característica:
$\det(A - \lambda I) = 0 \\$ 
$A - \lambda I = \begin{bmatrix} 1 - \lambda & 2 \\ 3 & 4 - \lambda \end{bmatrix} \\$
$\det(A - \lambda I) = \det\begin{bmatrix} 1 - \lambda & 2 \\ 3 & 4 - \lambda \end{bmatrix} \\$
$\text{Dada la ecuacion:} \quad (1 - \lambda)(4 - \lambda) - 6 = 0 \\$
$\text{Expandiendo el producto } (1 - \lambda)(4 - \lambda): \\$
$ = 1(4 - \lambda) - \lambda(4 - \lambda) = 4 - \lambda - 4\lambda + \lambda^2 = \lambda^2 - 5\lambda + 4 \\$
$\text{Sustituyendo en la ecuacion original:} \\$
$\lambda^2 - 5\lambda + 4 - 6 = 0 \\$
$\text{Simplificando: } \\$
$\lambda^2 - 5\lambda - 2 = 0 \\$
$\text{Resolviendo para la ecuacion} \\$
$\lambda^2 - 5\lambda - 2 = 0 \text{ usando la ecuacion cuadratica} \\$
$\lambda = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a} \\$
$\text{donde } a = 1, b = -5, c = -2. \\$
$\text{Sustituyendo esos valores} \\$
$\lambda = \frac{-(-5) \pm \sqrt{(-5)^2 - 4(1)(-2)}}{2(1)} = \frac{5 \pm \sqrt{25 + 8}}{2} = \frac{5 \pm \sqrt{33}}{2} \\$
$\text{Por lo tanto los autovalores son:} \\$
$\lambda_{1} = \frac{5 + \sqrt{33}}{2} \quad \text{o} \quad \lambda_{2} = \frac{5 - \sqrt{33}}{2} \\$

$\text{Para el calculo de los autovectores se debe satisfacer la ecuacion:} \\$
$( A - \lambda I) v = 0 \\$

$\text{Para } \lambda_{1} = \frac{5 + \sqrt{33}}{2}\\$
$(A - \lambda_{1} I)v = \begin{bmatrix} 1 - \lambda_{1} & 2 \\ 3 & 4 - \lambda_{1} \end{bmatrix} \begin{bmatrix} v_{1} \\ v_{2} \end{bmatrix} = 0\\$

$\text{Para } \lambda_{2} = \quad \lambda_{2} = \frac{5 - \sqrt{33}}{2}\\$
$(A - \lambda_{1} I)v = \begin{bmatrix} 1 - \lambda_{2} & 2 \\ 3 & 4 - \lambda_{2} \end{bmatrix} \begin{bmatrix} v_{1} \\ v_{2} \end{bmatrix} = 0\\$




**Ejercicio 1.2 (25 puntos)**

En una celda de código y utilizando la función eig de numpy, calcule los auto-valores y auto-vectores y haga las operaciones en el código para mostrar que se cumple: $A\,\vec{x} = \lambda\vec{x}$ (No olvide las pequeñas posibles diferencias por precisión de la representación numérica).



---

## Parte 2


Realice lo siguiente: **(40 puntos)**
1. Similar a los ejemplos vistos, aplíquele la estrategia PCA a los datos en el archivo adjunto "data_banknote_authentication.csv" (el $Y$ corresponde a la columna llamada clase).
1. En este caso use los tres primeros componentes principales (no dos como en el ejemplo).
1. El ejercicio termina graficando la varianza acumulada versus los componentes principales.

---



In [28]:
%matplotlib inline

import pandas as pd
import numpy as np
#import sklearn.datasets
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = [8, 4]


archivo = "data_banknote_authentication.csv"
data_banknote = pd.read_csv(archivo, header = 0 , delimiter = ';')
datos = pd.DataFrame(data_banknote).to_numpy()

#print(data_banknote)
X=datos[0:datos.shape[0]  , 0:3]
print(X)
# Escalar los datos en X
X_zscaled = (X - X.mean()) / X.std(ddof=1)
print( X_zscaled )

#datos[0:datos.shape[0] , 0:7 ]
Y_dataFrame = pd.DataFrame(data_banknote, columns=['class'])
Y=pd.DataFrame(Y_dataFrame).to_numpy()


dimensiones = data_banknote.shape
filas, columnas = dimensiones

print("------------------------------------------------------")
print("Filas", filas)
print("Columnas", columnas)
print("------------------------------------------------------")

#X = pd.DataFrame(data_banknote.data, data_banknote.feature_names)


[[  3.6216    8.6661   -2.8073 ]
 [  4.5459    8.1674   -2.4586 ]
 [  3.866    -2.6383    1.9242 ]
 ...
 [ -3.7503  -13.4586   17.5932 ]
 [ -3.5637   -8.3827   12.393  ]
 [ -2.5419   -0.65804   2.6842 ]]
[[ 0.52051213  1.62824337 -0.89122209]
 [ 0.72348091  1.5187329  -0.8146504 ]
 [ 0.57418039 -0.85411107  0.14777688]
 ...
 [-1.09829723 -3.23016107  3.58856202]
 [-1.05732139 -2.11553465  2.44664034]
 [-0.83294241 -0.41926205  0.31466671]]
------------------------------------------------------
Filas 1372
Columnas 5
------------------------------------------------------


___

## Parte 3

Como en el segundo gráfico del cuaderno visto en clase sobre PCA, grafique los tres mayores componentes principales utilizando la bibioteca **plotly** https://plotly.com/python/3d-scatter-plots/  **(10 puntos)**


___